version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: leads-db  # Nome explícito
    environment:
      POSTGRES_DB: ${BD_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aguia -d leads_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - leads-net
    restart: unless-stopped

  leads-api:
    build: .
    container_name: leads-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      SPRING_PROFILES_ACTIVE: prod
      JAVA_OPTS: "-Xmx512m -Xms256m"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - leads-net
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:
    driver: local

networks:
  leads-net:
    driver: bridge
    name: leads-network